### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by llchan** [jfbercher/jupyter_latex_envs#12]
It looks like the top level module imports from `IPython`, `nbconvert`, and `traitlets`, but those are not listed as dependencies in `setup.py`.

**Comment by jfbercher** [comment]
That is right. Thanks for pointing it. I'll update the requirements in a coming update.

**Comment by jfbercher** [comment]
This was addressed in https://github.com/jfbercher/jupyter_latex_envs/commit/e7883124f7d8667001117cf71f28d4b803b459a5
Thanks!

**Comment by moble** [comment]
FYI, when installing from the git source, I had to run

    pip install -U certifi

I guess this has nothing to do with this code and is related to [this jupyter notebook issue](https://github.com/jupyter/notebook/issues/1977), but *maybe* it has something to do with these new requirements...  Anyway, I was all `conda update`d and it was still failing, so this might be helpful to other people doing the same thing I'm doing.
