### ISSUE TITLE
Some bug  about theorem's counter and div of latexdefs

### ISSUE THREAD

**Issue by shanhaiying** [jfbercher/jupyter_latex_envs#8]
jfbercher:
Please excuse me to bother you again. When I want to revise your latex_envs 1.3.02 to meet my demands. I found the following problem:
1. The size of  div element that contains latexdefs can be change by my touch pad. It is the blank area at the bottom of notebook.
2. The theorems have wrong label number when the markdown cell has no H1.  
3. The equation can not be display when \label{eq:...} is used. The reason may be  that labels are removed.

![image](https://cloud.githubusercontent.com/assets/1595652/19407792/fc4b6cec-92de-11e6-9f2c-76a10d7f4555.png)

How to fix them.  Thanks!

**Comment by jfbercher** [comment]
Hi @shanhaiying 
No problem, reporting bugs/difficulties helps improving the extension. So it is welcome.
I have not these problems myself. 
1. Normally the div which embed the definitions in latexdefs.tex is not attached to the body. So it shouldn't be displayed at all
2. The wrong label number in the "book/report style" should have been fixed in one of the recent versions here in the github repo, but  not have been uploaded yet to pypi. Please try to update from this github version and report here if it persists (and also if it works)
3. I have no problem with equation labels. Check if this is present in the last version. 

If you find issues, please give me enough information and step by step explanation, and perhaps an example file, so that I can reproduce. Thanks

**Comment by shanhaiying** [comment]
I  have update the extension from this github version. 
- The problem of wrong label number is still present.  The following is the code in the markdown cell:

![image](https://cloud.githubusercontent.com/assets/1595652/19563437/84fc3e72-9712-11e6-93ed-573f3fc4e5a4.png)

![image](https://cloud.githubusercontent.com/assets/1595652/19563450/9740ef74-9712-11e6-8fb3-f3b560601f1b.png)

The problem have been solved by modifying the relevant code in thmsInNb4.js as follow:

`var section = $(elt).parent().parent().prevAll('h1')[0]`
- I find that the problem about equation labels be caused by some duplicate label.
- The problem about the div which embed the definitions in latexdefs.tex also be solved.

**Comment by jfbercher** [comment]
@shanhaiying 
Thanks for reporting and for the contribution. I have integrated a code modification that should (hopefully) fix the section detection issue. Thanks for spotting. 

I have also released a new version, v. 1..3.1  where one of the main new feature is the ability for the users to specify their own environments (or modify title/attached counters) using a configuration file, see the [doc](https://rawgit.com/jfbercher/jupyter_latex_envs/master/src/latex_envs/static/doc/latex_env_doc.html#-What's-new-). I think it could be useful for your own developments/modifications. You are welcome to try it.
